In [6]:
import pandas as pd

In [ ]:
# Q. What is difference between Series and Dataframe?

# Series -(rows)--collection of elements --1D
# DataFrame --(rows,columns) --2D

# Series --similar to single column
# DataFrame --similar to an Excel table

# Series --Has an index
# DataFrame--has row and column indexes

# series --can contain different data type
# DataFrame --different columns can have different data types

In [ ]:
# To select rows and columns we have 2 options
# 1. loc: label based selection
# 2. iloc: index based selection

In [ ]:
# Q. What is loc and iloc

# Loc -Selects data using label/names
# it is label based
# Uses row/column names
# df.loc[row_label,column_label]

# iloc--Selects data using integer position
# position based
# uses row/column numbers
# df.iloc[row_position,column_position]

In [ ]:
# Q. iloc vs loc

# loc -- label based selection
# iloc --integer position based selection

# loc --uses rows/column labels
# iloc --uses row/column index position

# loc - df.loc[1,'name']
# iloc - df.iloc[1,0]

# loc - can use column names
# iloc --uses only integer position

# loc - endpoints in slices are included
# iloc - endpoint in slices is excluded

In [ ]:
# Assignment:
# Change column name: replace space with _
# Dont use rename operation

In [11]:
f = pd.read_csv('fifa_eda.csv')
f.head(3)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [12]:
f.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [14]:
f.columns = f.columns.str.replace(' ','_')
f.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred_Foot', 'International_Reputation',
       'Skill_Moves', 'Position', 'Joined', 'Contract_Valid_Until', 'Height',
       'Weight', 'Release_Clause'],
      dtype='object')

In [ ]:
# Assignment: In Value column we have missing values.
# So replace those using average of Value it self.

In [15]:
v_avg = f['Value'].mean().round(2)
print(v_avg)

2444.53

In [31]:
f.Value

0        110500.0
1         77000.0
2        118500.0
3         72000.0
4        102000.0
           ...
18202        60.0
18203        60.0
18204        60.0
18205        60.0
18206        60.0
Name: Value, Length: 18207, dtype: object

In [37]:
u = f.Value.fillna(v_avg,inplace=True)
u

In [34]:
f['Value'].isnull().sum()

np.int64(0)